### ISSUE TITLE
Midieditor 3.5.0 roadmap

### ISSUE THREAD

**Issue by jingkaimori** [jingkaimori/midieditor#5]
Midieditor 3.5.0 will based on [estwald's branch](https://github.com/Estwald/midieditor/), but add l10n support and other improvements.

- [x] migrate to xmake
- [x] improve matrix widgets, add multiple highlight style.
- [x] build this editor on msvc(rather than mingw)
- [ ] add l10n for all texts appeared on gui
- [ ] fix irregular gui, such as truncated text
    - [x] settings
    - [ ] piano
- [ ] revamp chord editing procedure
    - [ ] add algorithms from [musicpy](https://github.com/Rainbow-Dreamer/musicpy) by @Rainbow-Dreamer
- [ ] test this software on ubuntu jammy
- [ ] improve handling of text event
    - [ ] use karaoke banner to __play__ lyric text event
    - [ ] add interface to __edit__ text events
- [ ] improve handling of channel select event (`0x21`)
- [ ] improve handling of `select changed` protocol
